# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vngG0XT2BvtDB1Y1HMEPprNUjT_ZggsM
"""

# importando a biblioteca que possui as funções para data science
import pandas as pd

# variável utilizada para importar a base de dados
valores = pd.read_csv('telecom_users.csv')

# traz os primeiros 5 valores do arquivo
valores.head()

# traz a quantidade de linhas e colunas
valores.shape

# filtra dentro de um conjunto uma vez um determinado valor ( retorna todos os tipos, dependendo do contexto )
# valores['TipoContrato'].unique() --> funciona da mesma forma
valores.TipoContrato.unique()

# retorna a quantidade de valores de uma determinada coluna
valores.TipoContrato.value_counts()

valores.TipoContrato.value_counts().plot.hist()

# gerando um gráfico de histograma a partir da coluna 'MesesComoCliente'
valores.MesesComoCliente.plot.hist()

valores.MesesComoCliente.value_counts().plot.hist()

valores.MesesComoCliente.plot.box()

import plotly.express as px

grafico = px.box(valores, y="MesesComoCliente",title=f"Meses Como Cliente")
grafico.show()

# deleta a coluna Codigo
valores_preparados = valores.drop('Codigo', axis=1)

# deleta todos os campos nulos
valores_preparados = valores_preparados.dropna()

# deleta a coluna Unnamed
valores_preparados = valores_preparados.drop('Unnamed: 0', axis=1)

# deleta os valores duplicados
valores_preparados = valores_preparados.drop_duplicates()

# utilizado para substituir os valores nulos por algo
# valores_preparados = valores.fillna(0)

valores_preparados

# calcular a média de um determinado valor
valores_preparados.groupby('TipoContrato').ValorMensal.mean()